import = ["/home/tim/.config/alacritty/catppuccin-frappe.toml"]

[window]
dynamic_padding = true

[scrolling]
history = 100000 # maximum
multiplier = 9 # default: 3

[cursor]
thickness = 0.25 # in insert mode
unfocused_hollow = false

[font]
size = 14.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

# Key codes: https://docs.rs/winit/latest/winit/keyboard/enum.NamedKey.html

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u001B[9;5u" # Forward <C-Tab> to Vim

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u001B[9;6u" # Forward <C-S-Tab> to Vim

[[keyboard.bindings]]
key = "Return"
mods = "Control"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "+"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "PageUp"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
action = "ScrollPageDown"
