# Style strings:
# https://starship.rs/config/#style-strings
# https://starship.rs/advanced-config/#style-strings

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$username\
$hostname\
$directory\
$jobs\
$git_branch\
$git_commit\
$git_status\
$git_state\
$fill\
$memory_usage\
$status\
$cmd_duration\
$time\
$line_break\
$shlvl\
$character
"""

[username]
format = "[$user]($style)@"

[hostname]
ssh_symbol = ""

[directory]
truncation_length = 0
truncate_to_repo = false

[jobs]

[shlvl]
disabled = false
format = '[$symbol]($style)'
repeat = true
symbol = '❯'
repeat_offset = 1
threshold = 0
style = "black bold"

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
style = "green"

[git_commit]
tag_symbol = "#"
style = "green"

[git_status]
format = '([$ahead_behind$all_status]($style) )'
style = "green"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$count⇣$count"

[git_state]
style = "yellow"

[fill]
symbol = " "

[status]
disabled = false
format = "[$status( $signal_name)]($style) "
style = "black"

[memory_usage]
disabled = true
format = "[${ram_pct}]($style) "
style = "fg:black"
threshold = 0

[cmd_duration]
format = "[$duration]($style) "
style = "fg:black"
min_time = 0
show_milliseconds = true

[time]
disabled = false
format = "[$time]($style)"
style = "fg:black"

[line_break]
disabled = false

[character]
