
[selection]
save_to_clipboard = true

[window]
dynamic_padding = true

[scrolling]
history = 100000 # maximum
multiplier = 9 # default: 3

[cursor]
thickness = 0.25 # in insert mode
unfocused_hollow = false

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

# Key codes: https://docs.rs/winit/latest/winit/keyboard/enum.NamedKey.html

[[keyboard.bindings]]
key = "Return"
mods = "Control"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "+"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "PageUp"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
action = "SelectNextTab"

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
action = "SelectPreviousTab"

[general]
import = [
    "~/.config/alacritty/catppuccin-frappe.toml",
    "~/.config/alacritty/platform.toml"
]
