theme = "catppuccin_frappe"

[editor]
line-number = "relative"
auto-pairs = true
scrolloff = 0
shell = ["fish", "-c"]
idle-timeout = 0 # ms before autocomplete

[editor.cursor-shape]
insert = "block"
